---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ubuntu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      volumes:
        - name: test-vol
          persistentVolumeClaim:
            claimName: ubuntu-pvc
      containers:
        - name: ubuntu
          image: busybox:latest
          command:
          - sleep
          - "86400"
          volumeMounts:
            - mountPath: /shared_files
              name: test-vol
